WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

PLAYER_MOVEMENT_SPEED = 1
PLAYER_LOOK_SPEED = 100
PLAYER_JUMP_FORCE = 1

GRAVITY = 0.01
CELL_SIZE = 2
WALL_THICKNESS = 0.5
WALL_HEIGHT = 1
FLOOR_COLOR = (0, 0.5, 0)
FLOOR_THICKNESS = 0.1
ELEVATOR_THICKNESS = 0.1

MAZE_WIDTH = 5
MAZE_DEPTH = 5
MAZE_LEVELS = 3

REWARD_ROTATION_SPEED = 50

MAX_NUM_OF_LIGHTS = 10
