SHADERS_PATH = "Shaders"
MODELS_PATH = "Models"
TEXTURES_PATH = "Textures"

WORLD_WIDTH = 20
WORLD_DEPTH = 20

# World
FOV = 75
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
GRAVITY = 10

# Player
PLAYER_MOUSE_SPEED = 10
PLAYER_MOUSE_MAX_MIN_Y_VALUE = 45
PLAYER_JUMP_FORCE = 5
PLAYER_MOVEMENT_SPEED = 5

PLAYER_HEIGHT = 1
PLAYER_WIDTH = .6
PLAYER_DEPTH = .6

PLAYER_HEALTH = 100

# Rockets
ROCKET_SPEED = 20
ROCKET_FIRE_RATE = 1
ROCKET_LIFE_TIME = 50

ROCKET_HEIGHT = .2
ROCKET_WIDTH = .2
ROCKET_DEPTH = 1
