SHADERS_PATH = "Shaders"
MODELS_PATH = "Models"
TEXTURES_PATH = "Textures"

WORLD_WIDTH = 10
WORLD_DEPTH = 10

# World
FOV = 75
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
GRAVITY = 5


# Player
PLAYER_MOUSE_SPEED = 100
PLAYER_MOUSE_MAX_MIN_Y_VALUE = 45
PLAYER_JUMP_FORCE = 1
